### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by gmartynov** [pyToshka/vault-autounseal#14]
`
INFO | /app/./app.py:<module>:166 - Start Vault auto unseal
Traceback (most recent call last):
  File "/app/./app.py", line 168, in <module>
    get_seal_status()
  File "/app/./app.py", line 141, in get_seal_status
    if not get_seal.json()["initialized"]:
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

please explain how to use this tool in k8s with helm, I have vault installed in `vault `namespace with ingress configured for ui

which url should I define in helm settings - in-cluster vault service or web ui url ?

before deployment should I create k8s secrets containing root token and unlock keys manually in `vault `namespace ?
if yes, please give an example of `kubectl create secret` command for token and keys

should I define `namespace `somewhere in settings ?

please describe which additional steps I need to do manually to make it works.

**Comment by pyToshka** [comment]
Could you please check your [variables](https://github.com/pyToshka/vault-autounseal#system-environments)

**Comment by gmartynov** [comment]
variables inside container are:

```
VAULT_SECRET_SHARES=3
VAULT_SECRET_THRESHOLD=2
VAULT_URL=https://vault.web3d.opencascade.com
NAMESPACE=vault
VAULT_KEYS_SECRET=vault-keys
VAULT_ROOT_TOKEN_SECRET=vault-root-token
```

**Comment by pyToshka** [comment]
@gmartynov are you vault sealed?
This tool just for unseal Vault after installation.
As well make could help, checkout [this](https://github.com/pyToshka/vault-autounseal/blob/main/Makefile#L9)

**Comment by pyToshka** [comment]
Fell free to re-open
