### ISSUE TITLE
 licence details for source code ,docker image  kennyopennix/vault-autounseal 

### ISSUE THREAD

**Issue by sireeshau472** [pyToshka/vault-autounseal#23]
I hope this message finds you well. I'm reaching out to inquire about the licensing of the Vault auto unseal image in your repository. I've been exploring the project and am interested in understanding the terms and conditions under which the auto unseal image is distributed.

Could you please provide information on the licensing model, any usage restrictions, and whether there are specific requirements or considerations for incorporating this image into different projects?

Additionally, if there are any relevant links to licensing documentation or if the information is available in the README, please point me in the right direction.

I appreciate your time and assistance in clarifying this matter. Thank you!

**Comment by pyToshka** [comment]
hello license is BSD

**Comment by sireeshau472** [comment]
Thank you so much for your quick response
