### ISSUE TITLE
How to unseal vault with 3 key shares and threshold 

### ISSUE THREAD

**Issue by AkashRajvanshi** [pyToshka/vault-autounseal#33]
Hi, I have a vault with 3 key shares and a secret threshold of 3. How can I unseal it? Also, how can I pass multiple keys to the vault-keys secret?

kubectl create secret generic vault-root-token --from-literal=root_token=  
kubectl create secret generic vault-keys --from-literal=vault_keys=

**Comment by pyToshka** [comment]
Please read documentation this is auto-unseal mechanism, no need to create secrets

**Comment by AkashRajvanshi** [comment]
I just installed the helm chart with vault uri only, it throws this error:


```
INFO | 2024-02-29T16:52:30.175455+00:00 /app/app.py:<module>:324 - Discovered Vault instance(s): ['http://192.168.189.38:8200', 'http://192.168.112.119:8200', 'http://192.168.124.177:8200']
INFO | 2024-02-29T16:52:30.372634+00:00 /app/app.py:<module>:326 > /app/app.py:get_seal_status:142 - Unsealing Vault node http://192.168.189.38:8200
Traceback (most recent call last):
  File "/app/app.py", line 326, in <module>
    status = get_seal_status(replica_url, vault_initialized)
  File "/app/app.py", line 143, in get_seal_status
    read_secret(vault_keys, vault_instance_url)
  File "/app/app.py", line 86, in read_secret
    secret_client = api_instance.read_namespaced_secret(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 25013, in read_namespaced_secret
    return self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 25100, in read_namespaced_secret_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 244, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '0672bba2-8e68-49f7-8851-3838d961136c', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '671b5d51-b34e-4e36-892e-cc83e0d462e1', 'X-Kubernetes-Pf-Prioritylevel-Uid': '72b3dc68-3fac-4cfc-baa2-0e3a2020bdd2', 'Date': 'Thu, 29 Feb 2024 16:52:30 GMT', 'Content-Length': '194'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"vault-keys\" not found","reason":"NotFound","details":{"name":"vault-keys","kind":"secrets"},"code":404}
```

**Comment by pyToshka** [comment]
What’s your environment?
Which version do you use? 
What the steps for replacing?
How did you deploy?

**Comment by AkashRajvanshi** [comment]
> What’s your environment?
K3s (BareMetal 3 Node Cluster)

> Which version do you use?
latest (in chart.yaml : 0.5.1)

> What the steps for replacing?


> How did you deploy?
Just cloned the repo, deploy the helm chart to cluster with vault uri (http://vault.vault:8200)

**Comment by AkashRajvanshi** [comment]
If I manually create two secrets, vault-root-token with a vault token and vault-keys with unseal keys, then it works. However, if secret sharing and the threshold are set to more than 1, how can multiple keys be used in the secret?

**Comment by pyToshka** [comment]
[Here](https://github.com/pyToshka/vault-autounseal/blob/main/Makefile#L44)  example how to run in HA mode

**Comment by AkashRajvanshi** [comment]
> [Here](https://github.com/pyToshka/vault-autounseal/blob/main/Makefile#L44)  example how to run in HA mode

Yes, I used the same steps for setup. But getting above error.

**Comment by AkashRajvanshi** [comment]
Shows vault-keys secret not found!

**Comment by pyToshka** [comment]
@AkashRajvanshi i cant reproduce in my environment!

**Comment by AkashRajvanshi** [comment]
Hi, I previously installed Vault manually and then initialized it. after that I installed the Vault-Unseal chart. Should I install Vault and Vault-Unseal together so that Vault-Unseal initializes Vault by itself and stores the token and sealed keys in a secret?

**Comment by pyToshka** [comment]
@AkashRajvanshi  This application only for Unseal Vault https://developer.hashicorp.com/vault/docs/concepts/seal
