### ISSUE TITLE
Unseal does not work if the vault pod does not have yet an IP address assigned

### ISSUE THREAD

**Issue by sfc-gh-gmerticariu** [pyToshka/vault-autounseal#40]
We are deploying vault and vault-unseal from Helm using Pulumi. Sometimes, both pods start at the same time, which means that the Vault pod does not yet have an IP address. 

I checked the code and I discovered that there is no check for a valid IP address when iterating through the list of pods (https://github.com/pyToshka/vault-autounseal/blob/5bd1d941980b2b3b4b358c76c6d0db21459c05f1/app.py#L323). If the IP address is not assigned, then the Vault replica will look like e.g. ["http://None:8200"]. 

My suggestion would be to add a check for the Vault IP address and if it was not assigned, refetch the Pod list. To avoid an infinite loop, there can be a configuration that tells the program when it should stop waiting for the IP address.

If my proposal is desirable, I can create a PR with the fix.

**Comment by pyToshka** [comment]
Hi @sfc-gh-gmerticariu yes please, but keep in mind, Vault pods could be >= 1

**Comment by sfc-gh-gmerticariu** [comment]
@pyToshka unfortunately I don't have permissions to create a new branch for the PR. Could you please give the right permissions so I can create the PR?

**Comment by pyToshka** [comment]
@sfc-gh-gmerticariu you can fork repository and create pr.

**Comment by sfc-gh-gmerticariu** [comment]
Fix: https://github.com/pyToshka/vault-autounseal/pull/41

**Comment by pyToshka** [comment]
@sfc-gh-gmerticariu  please bump version :-) i reopened original issue
