### ISSUE TITLE
Errors after container startup

### ISSUE THREAD

**Issue by romanad** [pyToshka/vault-autounseal#51]
I'm trying to configure opennix/vault-autounseal:latest container in separate linux server for auto-unseal Vault CE which is deployed in Kubernetes, this is my docker manifest:

---

version: '3.7'

services:
  vault-autounseal:
    image: opennix/vault-autounseal:latest
    container_name: vault-autounseal
    environment:
      - VAULT_URL=https://vault.server.com:443
      - NAMESPACE=vault
      - VAULT_SECRET_SHARES=5
      - VAULT_SECRET_THRESHOLD=3
      - VAULT_ROOT_TOKEN_SECRET=vault-root-token
      - VAULT_KEYS_SECRET=vault-unseal-keys
    volumes:
      - /distrib/kubernetes/.kube/vbox:/root/.kube
    restart: unless-stopped

---	
	
After that I keep getting a lot of errors:

kubernetes.config.config_exception.ConfigException: Service host/port is not set.

File "/app/app.py", line 27, in get_kubernetes_client
config.load_kube_config()

Start Vault auto unseal
Traceback (most recent call last):
File "/app/app.py", line 307, in <module>
k8s_client = get_kubernetes_client()

kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

---

Can't understand what I'm doing wrong

**Comment by pyToshka** [comment]
Your yaml is not kubernetes deployment. Please read readme

**Comment by romanad** [comment]
> Your yaml is not kubernetes deployment. Please read readme

The thing is, in readme there is this phrase ‘The solution can be run as docker container or inside Kubernetes’.

Could you please clarify - the option of running the opennix/vault-autounseal:latest container on a separate server, such as an Ubuntu server, to unlock Vault CE deployed in Kubernetes - is this a working scenario?

**Comment by pyToshka** [comment]
> > Your yaml is not kubernetes deployment. Please read readme
> 
> The thing is, in readme there is this phrase ‘The solution can be run as docker container or inside Kubernetes’.
> 
> Could you please clarify - the option of running the opennix/vault-autounseal:latest container on a separate server, such as an Ubuntu server, to unlock Vault CE deployed in Kubernetes - is this a working scenario?

You should configure Kubernetes credentials in rigth way, i didn't test this case. Mostly this solution are not
- Production ready
- Tested outside Kubernetes/OpenShift

Code for getting credentials https://github.com/pyToshka/vault-autounseal/blob/main/app.py#L22

**Comment by romanad** [comment]
Thank you very much!
